### ISSUE TITLE
Add Slashdot

### ISSUE THREAD

**Issue by zmughal** [frankcash/HackerQueue#37]
[It](//slashdot.org/) doesn't have scoring though.

**Comment by zmughal** [comment]
This can probably be done via the [RSS](http://rss.slashdot.org/Slashdot/slashdotMain) feed. In fact, if you support feeds once, it should be possible to extend that to any site that uses RSS/Atom feeds.

**Comment by frankcash** [comment]
Yeah I basically went with web scraping because

1. I originally wanted to learn more about it
2. There was no API or RSS feed for Hacker News when I started
3. It presented more of a challenge
4. Requires service x in general to maintain their RSS capabilities

**Comment by rajat19** [comment]
Should I pick this up
And would it be from slashdot.org or technology.slashdot.org

**Comment by zmughal** [comment]
Oh sweet!! <3

**Comment by frankcash** [comment]
sorry @zmughal this never got implemented 😢
