### ISSUE TITLE
Self posts sometimes fail for lobste.rs

### ISSUE THREAD

**Issue by frankcash** [frankcash/HackerQueue#39]

**Comment by michaelsergio** [comment]
I have a fix I'm working on for this. 
It should be ready soon after I test it a bit more.
I think the way lobste.rs embedded their URL changed in the html changed at some point.
It will still use the same html scrapping approach with some minor changes.

Ideally, sometime in the future, it will be better to switch all the sources to their RSS feeds for better stability.

**Comment by frankcash** [comment]
Thank you.

I agree, I will look into this soon.  I've set aside time to work on HackerQueue this weekend (including adding slashdot)
