### ISSUE TITLE
Comment buttons too dark.

### ISSUE THREAD

**Issue by michaelsergio** [frankcash/HackerQueue#41]
The comment icons for Reddit and lobsters are very dark.
Its hard to tell when they have been clicked.

Maybe use the favicon colors:
http://www.redditstatic.com/favicon.ico
https://lobste.rs/apple-touch-icon-144.png

I would do this myself, but I'm not really sure how they were made and colorizing the icons in the gimp doesn't really give me the results I want.

**Comment by justiceotuya** [comment]
can i do this?

**Comment by frankcash** [comment]
If you want to I would greatly appreciate it!

**Comment by bkjoel** [comment]
I'll have a go at this as well, on it right now 👍

**Comment by frankcash** [comment]
hell yeah
