### ISSUE TITLE
HackerNews comment redirect is broken

### ISSUE THREAD

**Issue by frankcash** [frankcash/HackerQueue#45]

**Comment by frankcash** [comment]
It appears HackerNews changed their source code, I'll mess with it more over the next couple days.

**Comment by kme211** [comment]
@frankcash I can fix this.

**Comment by frankcash** [comment]
Awesome @kme211 !  Let me know if you get stuck!

**Comment by kme211** [comment]
@frankcash It looks like the number of comments may also be broken (displaying hours instead of comments), do you want me to fix that, too?

**Comment by frankcash** [comment]
That'd be great :)

**Comment by kme211** [comment]
I submitted a PR (my first!). Please let me know if I should have done anything different.

**Comment by frankcash** [comment]
Thank you so much for your contribution, I really appreciate it!  

:smile_cat:
