### ISSUE TITLE
Website appears to be down

### ISSUE THREAD

**Issue by sdaitzman** [frankcash/HackerQueue#46]
It has an article about Dr. Oz on it... has the server been hacked or something?

**Comment by frankcash** [comment]
This is interesting. I deleted the Digital Ocean server the other night since I'm all out of credit.  I just removed my DNS settings (for Digital Ocean) on NameCheap, that should fix it?

**Comment by alexbednarczyk** [comment]
No more Dr. OZ. Now it tries to connect to an IP(107.170.175.210) on port 3000 but fails.

**Comment by frankcash** [comment]
Will fix this tonight

**Comment by frankcash** [comment]
Once again, if someone would like to run a server w/ it or donate a server I will gladly manage it w/ hackerqueue (I still own the domain)

**Comment by frankcash** [comment]
I put it back up, but it's on Heroku!

If ya'll are still interested!

https://hackerqueue.herokuapp.com/

**Comment by sdaitzman** [comment]
Yay!!!! Thank you!!

**Comment by frankcash** [comment]
No problem :) I'll keep you updated if I do move it again
