### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by frankcash** [frankcash/HackerQueue#47]
The following functions need to be tested
- [ ] `reddit.parse`
- [ ] `hackernews.parse`
- [ ] `lobsters.parseLobsterElement` 

I personally like [mocha](https://mochajs.org/) and [chai](http://chaijs.com/)

**Comment by RobAWilkinson** [comment]
didn't see there was another issue but fixes #45 the problem with hacker news comments redirects

**Comment by tetreault** [comment]
can take a go at this one @frankcash

**Comment by frankcash** [comment]
Yes

**Comment by frankcash** [comment]
Once again, looking for anyone willing to write tests!
