### ISSUE TITLE
Add Travis-CI

### ISSUE THREAD

**Issue by frankcash** [frankcash/HackerQueue#48]
I'd like to see a Travis-CI added.

Should run tests #47

**Comment by gsrajadh** [comment]
@frankcash Can I work on this?

**Comment by frankcash** [comment]
@gsrajadh yes!  If you have any questions please let me know!

Right now the project only uses `npm test` to do [jshint](https://github.com/frankcash/HackerQueue/blob/master/package.json#L17) but that sould be good enough to get Travis going!

**Comment by gsrajadh** [comment]
Resolved in #49
